const FieldDataType = Object.freeze({
  NUMBER: 'NUMBER',
  PASSWORD: 'PASSWORD',
  TEXT: 'TEXT',
  TIME: 'TIME',
  DATE: 'DATE',
  DATETIME: 'DATETIME',
  EMAIL: 'EMAIL',
  CHECKBOX: 'CHECKBOX',
  SELECT: 'SELECT',
  MULTIPLE_SELECT: 'MULTIPLE_SELECT',
  SINGLE_SELECT: 'SINGLE_SELECT',
  DEFAULT: 'DEFAULT',
  DIVIDER: 'DIVIDER',
});

export default FieldDataType;
