export enum VideoEncodingPresets {
  ULTRAFAST = 'ULTRAFAST',
  SUPERFAST = 'SUPERFAST',
  VERYFAST = 'VERYFAST',
  FASTER = 'FASTER',
  FAST = 'FAST',
  MEDIUM = 'MEDIUM',
  SLOW = 'SLOW',
  SLOWER = 'SLOWER',
  VERYSLOW = 'VERYSLOW'
}
