#https://www.obytes.com/blog/react-native-ci-cd-github-action
#openssl base64 < NaviHomeClientAdHoc.mobileprovision | tr -d '\n' | tee NaviHomeClientAdHoc.base64.txt
#openssl base64 < cert.p12 | tr -d '\n' | tee cert.base64.txt
name: iOS Production Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  ios-build:
    name: iOS Production Build
    runs-on: macOS-latest

    steps:
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest-stable

      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 300000

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1.205.0
        with:
          ruby-version: 3.3.6
          bundler-cache: true

      - name: Restore Pods cache
        uses: actions/cache@v4
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pods
        run: pod install --repo-update
        working-directory: ./ios

      - name: Build IOS App (ad-hoc)
        uses: yukiarrr/ios-build-action@v1.12.0
        with:
          project-path: ios/NaviHomeClient.xcodeproj
          p12-base64: ${{ secrets.IOS_P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILE_PROVISION_BASE64 }}
          export-method: 'ad-hoc'
          code-signing-identity: ${{ secrets.IOS_CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.IOS_TEAM_ID }}
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          workspace-path: ios/NaviHomeClient.xcworkspace
          scheme: NaviHomeClient

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: ./**.ipa
