name: IOS Production Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  ios-build:
    name: IOS Production Build
    runs-on: macOS-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3.5.3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore node_modules from cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 300000

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Restore Pods cache
        uses: actions/cache@v2
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pods
        run: pod install --repo-update
        working-directory: ./ios

      - name: Build IOS App (ad-hoc)
        uses: yukiarrr/ios-build-action@v1.11.0
        with:
          project-path: ios/NaviHomeClient.xcodeproj
          p12-base64: ${{ secrets.IOS_P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILE_PROVISION_BASE64 }}
          export-method: 'ad-hoc'
          code-signing-identity: 'iOS Distribution'
          team-id: ${{ secrets.IOS_TEAM_ID }}
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          workspace-path: ios/NaviHomeClient.xcworkspace
          scheme: NaviHomeClient

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ipa
          path: ./**.ipa
